using Rascor.Modules.ToolboxTalks.Domain.Enums;

namespace Rascor.Modules.ToolboxTalks.Application.Services;

/// <summary>
/// Service for generating multiple-choice quiz questions from toolbox talk content using AI.
/// Generates questions from video transcripts and/or PDF content.
/// </summary>
public interface IAiQuizGenerationService
{
    /// <summary>
    /// Generates quiz questions from the provided content using Claude AI.
    /// </summary>
    /// <param name="toolboxTalkId">The ID of the toolbox talk (for logging purposes)</param>
    /// <param name="combinedContent">The combined content from video transcript and/or PDF</param>
    /// <param name="videoFinalPortionContent">Content from the final 20% of the video (for final portion question)</param>
    /// <param name="hasVideoContent">Whether the combined content includes video transcript</param>
    /// <param name="hasPdfContent">Whether the combined content includes PDF text</param>
    /// <param name="minimumQuestions">Minimum number of questions to generate (default: 5)</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Result containing generated questions or error information</returns>
    Task<QuizGenerationResult> GenerateQuizAsync(
        Guid toolboxTalkId,
        string combinedContent,
        string? videoFinalPortionContent,
        bool hasVideoContent,
        bool hasPdfContent,
        int minimumQuestions = 5,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Result of an AI quiz generation operation.
/// </summary>
/// <param name="Success">Whether the generation was successful</param>
/// <param name="Questions">List of generated quiz questions</param>
/// <param name="ErrorMessage">Error message if generation failed</param>
/// <param name="TokensUsed">Number of tokens used in the API call</param>
/// <param name="HasFinalPortionQuestion">Whether at least one question is from the video final portion</param>
public record QuizGenerationResult(
    bool Success,
    List<GeneratedQuizQuestion> Questions,
    string? ErrorMessage,
    int TokensUsed,
    bool HasFinalPortionQuestion);

/// <summary>
/// A quiz question generated by the AI from the source content.
/// </summary>
/// <param name="SortOrder">Display order of this question</param>
/// <param name="QuestionText">The question text</param>
/// <param name="Options">List of 4 answer options</param>
/// <param name="CorrectAnswerIndex">Index of the correct answer (0-3)</param>
/// <param name="Source">Source of the question content (Video or Pdf)</param>
/// <param name="IsFromVideoFinalPortion">Whether this question is from the final 20% of the video</param>
/// <param name="VideoTimestamp">Approximate timestamp in the video (e.g., "8:30") if from video</param>
public record GeneratedQuizQuestion(
    int SortOrder,
    string QuestionText,
    List<string> Options,
    int CorrectAnswerIndex,
    ContentSource Source,
    bool IsFromVideoFinalPortion,
    string? VideoTimestamp);
