using Rascor.Modules.ToolboxTalks.Domain.Enums;

namespace Rascor.Modules.ToolboxTalks.Application.Services;

/// <summary>
/// Service for generating toolbox talk sections from content using AI.
/// Generates concise sections (key points) from video transcripts and/or PDF content.
/// </summary>
public interface IAiSectionGenerationService
{
    /// <summary>
    /// Generates sections from the provided content using Claude AI.
    /// Each section contains a title and 4-5 line paragraph covering an important safety topic.
    /// </summary>
    /// <param name="toolboxTalkId">The ID of the toolbox talk (for logging purposes)</param>
    /// <param name="combinedContent">The combined content from video transcript and/or PDF</param>
    /// <param name="hasVideoContent">Whether the combined content includes video transcript</param>
    /// <param name="hasPdfContent">Whether the combined content includes PDF text</param>
    /// <param name="minimumSections">Minimum number of sections to generate (default: 7)</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Result containing generated sections or error information</returns>
    Task<SectionGenerationResult> GenerateSectionsAsync(
        Guid toolboxTalkId,
        string combinedContent,
        bool hasVideoContent,
        bool hasPdfContent,
        int minimumSections = 7,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Result of an AI section generation operation.
/// </summary>
/// <param name="Success">Whether the generation was successful</param>
/// <param name="Sections">List of generated sections</param>
/// <param name="ErrorMessage">Error message if generation failed</param>
/// <param name="TokensUsed">Number of tokens used in the API call</param>
public record SectionGenerationResult(
    bool Success,
    List<GeneratedSection> Sections,
    string? ErrorMessage,
    int TokensUsed);

/// <summary>
/// A section generated by the AI from the source content.
/// </summary>
/// <param name="SortOrder">Display order of this section</param>
/// <param name="Title">Title of the section</param>
/// <param name="Content">Content paragraph (4-5 lines)</param>
/// <param name="Source">Source of the content (Video, Pdf, or Both)</param>
public record GeneratedSection(
    int SortOrder,
    string Title,
    string Content,
    ContentSource Source);
