using MediatR;

namespace Rascor.Modules.ToolboxTalks.Application.Commands.SmartGenerateContent;

/// <summary>
/// Command for smart content generation that automatically reuses existing content
/// from duplicate sources and only generates what's missing via AI.
/// </summary>
public record SmartGenerateContentCommand : IRequest<SmartGenerateContentResult>
{
    public Guid TenantId { get; init; }
    public Guid ToolboxTalkId { get; init; }
    public bool GenerateSections { get; init; }
    public bool GenerateQuestions { get; init; }
    public bool GenerateSlideshow { get; init; }
    public string SourceLanguageCode { get; init; } = "en";
    public int MinimumSections { get; init; } = 7;
    public int MinimumQuestions { get; init; } = 5;
    public int PassThreshold { get; init; } = 80;

    /// <summary>Whether the content source includes video</summary>
    public bool IncludeVideo { get; init; }

    /// <summary>Whether the content source includes PDF</summary>
    public bool IncludePdf { get; init; }

    /// <summary>SignalR connection ID for progress updates during AI generation</summary>
    public string? ConnectionId { get; init; }
}

/// <summary>
/// Result of a smart content generation operation.
/// Shows what was copied from existing content vs what was generated by AI.
/// </summary>
public class SmartGenerateContentResult
{
    // What was copied (from existing source)
    public int SectionsCopied { get; set; }
    public int QuestionsCopied { get; set; }
    public bool SlideshowCopied { get; set; }
    public int TranslationsCopied { get; set; }
    public bool SubtitlesCopied { get; set; }

    // What was generated (new AI calls)
    public int SectionsGenerated { get; set; }
    public int QuestionsGenerated { get; set; }
    public bool SlideshowGenerated { get; set; }

    // Source info (for UI display)
    public string? ContentCopiedFromTitle { get; set; }

    // Generation metadata
    public bool Success { get; set; } = true;
    public string? ErrorMessage { get; set; }

    /// <summary>Whether AI generation was queued as a background job (via Hangfire)</summary>
    public bool GenerationJobQueued { get; set; }

    /// <summary>The Hangfire job ID if a background generation was queued</summary>
    public string? GenerationJobId { get; set; }
}
